### ISSUE TITLE
Not working with WHMCS v8.8.0

### ISSUE THREAD

**Issue by championc** [hostmedia/whmcs-sendgrid-usage-widget#2]
When I try and work with v8.8.0, it crashes the main index.php page loading

**Comment by hostmedia** [comment]
Sorry for the delayed reply in seeing your reported issue - we have tested on WHMCS 8.8.0 and it is running fine, if it causes a break in your index page, please make sure sendgrid is accessible and configured correctly in the file as that might cause the widget to break. There were fixes for PHP8 in our last commits which might also resolve the issue.

If you continue to get the issue please can you provide the PHP version and any error logs so we can see what might be causing the problem.
